#!/usr/bin/env node
// Single-command dev start. From a fresh clone:
//   npm install
//   npm run dev
// gets the local stack up, env vars in place, and Expo serving — no
// docs to follow, no "did you copy .env.example?" gotchas.

import { spawn, spawnSync } from 'node:child_process';
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

const yellow = (s) => `\x1b[33m${s}\x1b[0m`;
const cyan = (s) => `\x1b[36m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

// ----------------------------------------------------------------------------
// 1. Verify CLI is installed and read both versions.
// ----------------------------------------------------------------------------

const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));
const wantedCliVersion = pkg.supabase?.cli_version;
if (!wantedCliVersion) {
  console.error('package.json#supabase.cli_version is missing.');
  process.exit(1);
}

const versionProbe = spawnSync('supabase', ['--version'], { encoding: 'utf8' });
if (versionProbe.error || versionProbe.status !== 0) {
  console.error(
    'Supabase CLI not found on PATH. Install it from https://supabase.com/docs/guides/cli',
  );
  process.exit(1);
}
const localCliVersion = versionProbe.stdout.trim();
if (localCliVersion !== wantedCliVersion) {
  console.warn(
    yellow(
      `! Supabase CLI mismatch — local ${localCliVersion}, package.json wants ${wantedCliVersion}. ` +
        `CI uses package.json's value, so subtle behaviour differences are possible.`,
    ),
  );
}

// ----------------------------------------------------------------------------
// 2. Make sure the local stack is up. supabase status exits 0 if running,
//    non-zero otherwise — we boot it if needed.
// ----------------------------------------------------------------------------

const statusCheck = spawnSync('supabase', ['status'], {
  cwd: projectRoot,
  stdio: 'ignore',
});
if (statusCheck.status !== 0) {
  console.log(cyan('› Starting local Supabase stack…'));
  const start = spawnSync('supabase', ['start'], {
    cwd: projectRoot,
    stdio: 'inherit',
  });
  if (start.status !== 0) {
    console.error('supabase start failed. Is Docker running?');
    process.exit(1);
  }
}

// ----------------------------------------------------------------------------
// 3. Ensure .env.local exists. If absent, generate one populated from
//    `supabase status -o env` so the dev never has to copy/paste.
//    Existing .env.local is left alone — devs who switched to hosted keep
//    their settings.
// ----------------------------------------------------------------------------

const envLocalPath = join(projectRoot, '.env.local');
if (!existsSync(envLocalPath)) {
  const envOut = spawnSync('supabase', ['status', '-o', 'env'], {
    cwd: projectRoot,
    encoding: 'utf8',
  });
  if (envOut.status !== 0) {
    console.error('Failed to read supabase status -o env.');
    process.exit(1);
  }
  // supabase status -o env emits lines like `API_URL="http://127.0.0.1:54321"`
  // and `ANON_KEY="sb_publishable_..."`. We map those onto the EXPO_PUBLIC_
  // names the app reads.
  const lines = envOut.stdout.split('\n');
  const get = (key) => {
    const hit = lines.find((l) => l.startsWith(`${key}=`));
    if (!hit) return null;
    return hit.slice(key.length + 1).replace(/^"|"$/g, '');
  };
  const apiUrl = get('API_URL');
  const anonKey = get('ANON_KEY');
  if (!apiUrl || !anonKey) {
    console.error(
      'Could not derive API_URL / ANON_KEY from supabase status. Inspect with `supabase status -o env`.',
    );
    process.exit(1);
  }
  writeFileSync(
    envLocalPath,
    [
      '# Auto-generated by `npm run dev`. Edit to point at hosted Supabase.',
      `EXPO_PUBLIC_SUPABASE_URL=${apiUrl}`,
      `EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
      '',
    ].join('\n'),
  );
  console.log(cyan('› Wrote .env.local pointing at the local Supabase stack.'));
} else {
  console.log(dim('› .env.local already exists, leaving it alone.'));
}

// ----------------------------------------------------------------------------
// 4. Hand off to Expo. Inherit stdio so Ctrl+C, the dev menu, etc all work.
// ----------------------------------------------------------------------------

const expo = spawn('npx', ['expo', 'start', '--web'], {
  cwd: projectRoot,
  stdio: 'inherit',
});
expo.on('exit', (code) => process.exit(code ?? 0));
