#!/usr/bin/env bash
# SessionStart hook for Claude Code sessions (registered in
# .claude/settings.json). Cloud containers reset onto a stale
# autogenerated claude/* branch between sessions, which has already
# produced one wrong-branch commit — this restores a synced main
# whenever that's provably safe, and otherwise only reports.
#
# Safe on developer machines too: on main (or any non-claude/* branch)
# it just fetches and prints one status line.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

git config --local --get user.email >/dev/null \
  || git config --local user.email noreply@anthropic.com
git config --local --get user.name >/dev/null \
  || git config --local user.name Claude

git fetch origin main --quiet

branch="$(git rev-parse --abbrev-ref HEAD)"

# Auto-switch only when nothing can be lost:
#   - throwaway claude/* branch
#   - clean working tree
#   - every commit already pushed. Compare against the branch's own
#     upstream, not origin/main: squash-merged branches are forever
#     "ahead" of main by SHA, so an origin/main comparison would never
#     fire on exactly the stale branches that cause the problem.
if [[ "$branch" == claude/* ]] && [[ -z "$(git status --porcelain)" ]]; then
  if upstream="$(git rev-parse --abbrev-ref '@{upstream}' 2>/dev/null)"; then
    unpushed="$(git rev-list --count "$upstream"..HEAD)"
  else
    unpushed="$(git rev-list --count origin/main..HEAD)"
  fi
  if [[ "$unpushed" == "0" ]]; then
    git checkout main --quiet
    git pull --ff-only origin main --quiet
    echo "session-start: switched from $branch to synced main ($(git rev-parse --short HEAD))"
    exit 0
  fi
fi

echo "session-start: staying on $(git status -sb | head -1)"
