// AI front desk — inbound SMS webhook (Twilio).
//
// Twilio POSTs every text sent to a gym's number here. No JWT (Twilio
// carries none); the guard is the X-Twilio-Signature HMAC over the exact
// public URL + params. The reply is generated by a Claude tool loop that
// can take longer than Twilio's 15s webhook deadline, so we return empty
// TwiML immediately and finish the turn in EdgeRuntime.waitUntil — the
// reply goes out via the Twilio REST API, not the webhook response.
//
// Required env (SUPABASE_* injected by the platform):
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_ANON_KEY,
//   TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN
// Optional:
//   ANTHROPIC_API_KEY (absent -> static handoff reply, infer-import style)
//   LEAD_AGENT_MODEL (default claude-sonnet-5)
//   APP_ORIGIN (default https://app.jointemple.io)
//   LEAD_AGENT_SMS_URL (override the signed URL if a proxy rewrites it)

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

import {
  appendMessage,
  buildSystemPrompt,
  fetchCoachingText,
  fetchGymSnapshot,
  getOrCreateConversation,
  isStopKeyword,
  loadHistory,
  resolveGymByNumber,
  runAgentLoop,
  sendTwilioSms,
  SMS_TOOLS,
  twiml,
  validateTwilioSignature,
  type AgentGym,
  type Conversation,
} from '../_shared/lead-agent.ts';

declare const EdgeRuntime: { waitUntil(p: Promise<unknown>): void };

Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
  const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY');
  const TWILIO_SID = Deno.env.get('TWILIO_ACCOUNT_SID');
  const TWILIO_TOKEN = Deno.env.get('TWILIO_AUTH_TOKEN');
  if (!SUPABASE_URL || !SERVICE_KEY || !ANON_KEY || !TWILIO_SID || !TWILIO_TOKEN) {
    return new Response('Function is not configured', { status: 500 });
  }

  const form = await req.formData();
  const params: Record<string, string> = {};
  for (const [k, v] of form.entries()) params[k] = String(v);

  const url =
    Deno.env.get('LEAD_AGENT_SMS_URL') ?? `${SUPABASE_URL}/functions/v1/lead-agent-sms`;
  const valid = await validateTwilioSignature(
    TWILIO_TOKEN,
    url,
    params,
    req.headers.get('X-Twilio-Signature'),
  );
  if (!valid) return new Response('Bad signature', { status: 403 });

  const { MessageSid, From, To, Body } = params;
  if (!MessageSid || !From || !To) return twiml();

  // WhatsApp arrives on this same webhook, addressed
  // "whatsapp:+447700900123". The prefix is a wire detail and stays one:
  // agent_stop_conversation matches on phone, leads.phone is E.164, and
  // agent_capture_lead dedupes on it — storing the prefix would silently
  // stop all three matching for exactly the people using the newest
  // channel (0275).
  const channel: 'sms' | 'whatsapp' = From.startsWith('whatsapp:')
    ? 'whatsapp'
    : 'sms';
  const fromNumber = From.replace(/^whatsapp:/, '');
  const toNumber = To.replace(/^whatsapp:/, '');

  const service = createClient(SUPABASE_URL, SERVICE_KEY);
  const gym = await resolveGymByNumber(service, toNumber);
  if (!gym || !gym.settings.enabled) return twiml();

  const conversation = await getOrCreateConversation(
    service,
    gym.id,
    fromNumber,
    channel,
  );

  const body = (Body ?? '').trim();
  if (!body) return twiml();

  if (isStopKeyword(body)) {
    await appendMessage(service, conversation, 'lead', body, MessageSid);
    await service.rpc('agent_stop_conversation', {
      p_conversation_id: conversation.id,
    });
    // The texter may be a member rather than a lead, and until 0271 that
    // case suppressed nothing: agent_stop_conversation closes a thread and
    // clears a LEAD's consent. Twilio's Advanced Opt-Out would then block
    // delivery at the carrier while Temple went on queueing texts and
    // believing they arrived — worse than not honouring STOP at all,
    // because it looks like it worked.
    await service.rpc('member_stop_texts', {
      p_gym_id: gym.id,
      p_phone: fromNumber,
    });
    // Twilio Advanced Opt-Out sends the compliance reply itself.
    return twiml();
  }

  const fresh = await appendMessage(service, conversation, 'lead', body, MessageSid);
  if (!fresh) return twiml();

  // Handed-off threads belong to a human now; closed ones opted out. A
  // reply into a handed-off thread still pings the coach (hour-throttled
  // server-side) — before this, it landed silently.
  if (conversation.status !== 'active') {
    if (conversation.status === 'handed_off') {
      EdgeRuntime.waitUntil(
        notifyHandoffReply(service, gym.id, conversation.id, {
          supabaseUrl: SUPABASE_URL,
          anonKey: ANON_KEY,
        }).catch((e) => console.error('handoff reply notify failed', e)),
      );
    }
    return twiml();
  }

  // Spend guardrail: past the gym's daily outbound cap the AI stops
  // replying (bounded model + Twilio spend under a hostile or chatty
  // texter) and the thread goes to a human instead of going silent.
  const { count: sentToday } = await service
    .from('agent_messages')
    .select('id', { count: 'exact', head: true })
    .eq('gym_id', gym.id)
    .eq('role', 'agent')
    .gte('created_at', new Date(Date.now() - 24 * 3600 * 1000).toISOString());
  if ((sentToday ?? 0) >= gym.settings.daily_message_cap) {
    await service.rpc('agent_request_handoff', {
      p_conversation_id: conversation.id,
      p_reason: 'Daily message cap reached',
    });
    return twiml();
  }

  EdgeRuntime.waitUntil(
    reply(service, gym, conversation, {
      supabaseUrl: SUPABASE_URL,
      anonKey: ANON_KEY,
      twilioSid: TWILIO_SID,
      twilioToken: TWILIO_TOKEN,
    }).catch((e) => console.error('lead-agent-sms reply failed', e)),
  );

  return twiml();
});

async function notifyHandoffReply(
  // deno-lint-ignore no-explicit-any
  service: any,
  gymId: string,
  conversationId: string,
  env: { supabaseUrl: string; anonKey: string },
): Promise<void> {
  const { error } = await service.rpc('agent_notify_handoff_reply', {
    p_conversation_id: conversationId,
  });
  if (error) {
    console.error('agent_notify_handoff_reply failed', error.message);
    return;
  }
  // Best-effort drain so the email leaves now (mirrors request_handoff).
  try {
    await fetch(`${env.supabaseUrl}/functions/v1/send-lead-notifications`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        apikey: env.anonKey,
        Authorization: `Bearer ${env.anonKey}`,
      },
      body: JSON.stringify({ gym_id: gymId }),
    });
  } catch {
    // queue stays drainable from the owner screen
  }
}

async function reply(
  // deno-lint-ignore no-explicit-any
  service: any,
  gym: AgentGym,
  conversation: Conversation,
  env: { supabaseUrl: string; anonKey: string; twilioSid: string; twilioToken: string },
): Promise<void> {
  const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
  const appOrigin = (Deno.env.get('APP_ORIGIN') ?? 'https://app.jointemple.io').replace(
    /\/+$/,
    '',
  );

  const ctx = {
    service,
    gym,
    conversation,
    channel: 'sms' as const,
    appOrigin,
    twilio: { accountSid: env.twilioSid, authToken: env.twilioToken },
    supabaseUrl: env.supabaseUrl,
    anonKey: env.anonKey,
  };

  let text: string | null = null;
  if (apiKey) {
    const [snapshot, history, coaching] = await Promise.all([
      fetchGymSnapshot(service, gym),
      loadHistory(service, conversation.id),
      fetchCoachingText(service, gym.id),
    ]);
    text = await runAgentLoop({
      apiKey,
      model: Deno.env.get('LEAD_AGENT_MODEL') ?? 'claude-sonnet-5',
      system: buildSystemPrompt(gym, snapshot, conversation.channel, coaching),
      messages: history,
      tools: SMS_TOOLS,
      ctx,
    });
  }

  if (!text) {
    // No model available (or the loop died): don't leave the prospect
    // hanging — promise a human and mark the thread handed off.
    text = `Thanks for getting in touch with ${gym.name}! A coach will ${
      conversation.channel === 'whatsapp' ? 'message' : 'text'
    } you back shortly.`;
    await service.rpc('agent_request_handoff', {
      p_conversation_id: conversation.id,
      p_reason: apiKey ? 'Agent could not generate a reply' : 'Agent not configured',
    });
  }

  // The prefix goes back on at the wire, both ends — Twilio routes a
  // WhatsApp message by the address shape, not by the account.
  const wire = (n: string) =>
    conversation.channel === 'whatsapp' ? `whatsapp:${n}` : n;
  const sent = await sendTwilioSms(
    env.twilioSid,
    env.twilioToken,
    wire(gym.settings.phone_number),
    wire(conversation.phone),
    text,
    gym.isDemo,
  );
  if (sent.sid) {
    await appendMessage(service, conversation, 'agent', text, sent.sid);
  } else {
    console.error('lead-agent-sms send failed', sent.error);
  }
}
