// AI front desk — inbound SMS webhook (Twilio).
//
// Twilio POSTs every text sent to a gym's number here. No JWT (Twilio
// carries none); the guard is the X-Twilio-Signature HMAC over the exact
// public URL + params. The reply is generated by a Claude tool loop that
// can take longer than Twilio's 15s webhook deadline, so we return empty
// TwiML immediately and finish the turn in EdgeRuntime.waitUntil — the
// reply goes out via the Twilio REST API, not the webhook response.
//
// Required env (SUPABASE_* injected by the platform):
//   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_ANON_KEY,
//   TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN
// Optional:
//   ANTHROPIC_API_KEY (absent -> static handoff reply, infer-import style)
//   LEAD_AGENT_MODEL (default claude-sonnet-5)
//   APP_ORIGIN (default https://app.jointemple.io)
//   LEAD_AGENT_SMS_URL (override the signed URL if a proxy rewrites it)

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

import {
  appendMessage,
  buildSystemPrompt,
  fetchGymSnapshot,
  getOrCreateConversation,
  isStopKeyword,
  loadHistory,
  resolveGymByNumber,
  runAgentLoop,
  sendTwilioSms,
  SMS_TOOLS,
  twiml,
  validateTwilioSignature,
  type AgentGym,
  type Conversation,
} from '../_shared/lead-agent.ts';

declare const EdgeRuntime: { waitUntil(p: Promise<unknown>): void };

Deno.serve(async (req: Request) => {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });

  const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
  const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY');
  const TWILIO_SID = Deno.env.get('TWILIO_ACCOUNT_SID');
  const TWILIO_TOKEN = Deno.env.get('TWILIO_AUTH_TOKEN');
  if (!SUPABASE_URL || !SERVICE_KEY || !ANON_KEY || !TWILIO_SID || !TWILIO_TOKEN) {
    return new Response('Function is not configured', { status: 500 });
  }

  const form = await req.formData();
  const params: Record<string, string> = {};
  for (const [k, v] of form.entries()) params[k] = String(v);

  const url =
    Deno.env.get('LEAD_AGENT_SMS_URL') ?? `${SUPABASE_URL}/functions/v1/lead-agent-sms`;
  const valid = await validateTwilioSignature(
    TWILIO_TOKEN,
    url,
    params,
    req.headers.get('X-Twilio-Signature'),
  );
  if (!valid) return new Response('Bad signature', { status: 403 });

  const { MessageSid, From, To, Body } = params;
  if (!MessageSid || !From || !To) return twiml();

  const service = createClient(SUPABASE_URL, SERVICE_KEY);
  const gym = await resolveGymByNumber(service, To);
  if (!gym || !gym.settings.enabled) return twiml();

  const conversation = await getOrCreateConversation(service, gym.id, From, 'sms');

  const body = (Body ?? '').trim();
  if (!body) return twiml();

  if (isStopKeyword(body)) {
    await appendMessage(service, conversation, 'lead', body, MessageSid);
    await service.rpc('agent_stop_conversation', {
      p_conversation_id: conversation.id,
    });
    // Twilio Advanced Opt-Out sends the compliance reply itself.
    return twiml();
  }

  const fresh = await appendMessage(service, conversation, 'lead', body, MessageSid);
  if (!fresh) return twiml();

  // Handed-off threads belong to a human now; closed ones opted out.
  if (conversation.status !== 'active') return twiml();

  EdgeRuntime.waitUntil(
    reply(service, gym, conversation, {
      supabaseUrl: SUPABASE_URL,
      anonKey: ANON_KEY,
      twilioSid: TWILIO_SID,
      twilioToken: TWILIO_TOKEN,
    }).catch((e) => console.error('lead-agent-sms reply failed', e)),
  );

  return twiml();
});

async function reply(
  // deno-lint-ignore no-explicit-any
  service: any,
  gym: AgentGym,
  conversation: Conversation,
  env: { supabaseUrl: string; anonKey: string; twilioSid: string; twilioToken: string },
): Promise<void> {
  const apiKey = Deno.env.get('ANTHROPIC_API_KEY');
  const appOrigin = (Deno.env.get('APP_ORIGIN') ?? 'https://app.jointemple.io').replace(
    /\/+$/,
    '',
  );

  const ctx = {
    service,
    gym,
    conversation,
    channel: 'sms' as const,
    appOrigin,
    twilio: { accountSid: env.twilioSid, authToken: env.twilioToken },
    supabaseUrl: env.supabaseUrl,
    anonKey: env.anonKey,
  };

  let text: string | null = null;
  if (apiKey) {
    const snapshot = await fetchGymSnapshot(service, gym);
    const history = await loadHistory(service, conversation.id);
    text = await runAgentLoop({
      apiKey,
      model: Deno.env.get('LEAD_AGENT_MODEL') ?? 'claude-sonnet-5',
      system: buildSystemPrompt(gym, snapshot, 'sms'),
      messages: history,
      tools: SMS_TOOLS,
      ctx,
    });
  }

  if (!text) {
    // No model available (or the loop died): don't leave the prospect
    // hanging — promise a human and mark the thread handed off.
    text = `Thanks for getting in touch with ${gym.name}! A coach will text you back shortly.`;
    await service.rpc('agent_request_handoff', {
      p_conversation_id: conversation.id,
      p_reason: apiKey ? 'Agent could not generate a reply' : 'Agent not configured',
    });
  }

  const sent = await sendTwilioSms(
    env.twilioSid,
    env.twilioToken,
    gym.settings.phone_number,
    conversation.phone,
    text,
  );
  if (sent.sid) {
    await appendMessage(service, conversation, 'agent', text, sent.sid);
  } else {
    console.error('lead-agent-sms send failed', sent.error);
  }
}
